projecthorus/sondehub-tracker

- js/app.js
- js/tracker.js
Uses `gps_time` from the row as the position_id so that we only grab newish data. We remove the seconds and milliseconds so that the backend has an easier time caching requests that come in (to prevent overloading elasticsearch)
> Send position id to backend so we don't download the entire datanew each time

- js/tracker.js
When rendering ~700 markers Leaflet slowed considerably as each marker is an individual DOM.
I have switched to circleMarkers which render onto canvas so the performance is maintained.
> Switch to circle marker for launch site icons

- js/app.js
- js/tracker.js
The high-fidelity API should now kick in properly.
> API Fix + Nyan mode

- js/plot_config.js
- js/tracker.js
- manifest.json
**Fixes**
- Titles now positioned correctly in nyan mode
- Manifest updated to hopefully solve splash screen colour mismatch
- Enable/disable path button now works properly on nyan mode
- Nyan paths now get deleted when refreshing
- Launch site popups work when under day/night overlay
- Images in sidebar now positioned correctly on mobile
**Features**
- The marker on graph hover feature is back (sometimes it throws an error in console)
> bug fixes + marker return!

- css/main.css
- js/tracker.js
**New Features**
- The tracker can now display any individual sonde in the SondeHub database by using the modern APIs if legacy fail
- There are now links to the card page for sonde
**Fixes**
- button formatting sonde sidebar
- search and time update now always works
> Support for displaying old sonde + fixes

- css/main.css
- index.html
- js/tracker.js
**Features**
- We can now display sondes which were imported into the database from V1.
- We can now filter by type by entering one of the following in the search box:
`["RS92", "RS92-SGP", "RS92-NGP", "RS41", "RS41-SG", "RS41-SGP", "RS41-SGM", "DFM", "DFM06", "DFM09", "DFM17", "M10", "M20", "iMet-4", "iMet-54", "LMS6", "LMS6-400", "LMS6-1680", "iMS-100", "MRZ"]`
**Fixes**
- Formatting on mobile
- Updated webpage
> Mobile fixes, SondeHub V1 Support, Filter by type

- js/app.js
- js/tracker.js
I have attempted to fix the zoom issue using some less bad code.
I have also learned my lesson and will try on testing first :)
> Fix attempt

- js/tracker.js
With the websockets message looked bad in old position on mobile.
> Move last updated text

- js/tracker.js
- Show Tawhiri model used on landing marker
- Show ascent rate, burst altitude, and descent rate assumptions on landing marker
- Show launch schedule on station popup
- Show GitHub issue link on station popup
> Prediction Improvments

- js/tracker.js
- launchSites.json
added notes field and removed next flight
> prediction changes

- js/tracker.js
Update recovery information
Switch to using alt for icon colour as a test
Default to latest month for showing data
> Historical fixes

- js/tracker.js
This PR fixes #244 issue.
When there are multiple chase cars with the same color at site load, since the HTML img element is stored in icon_cache before the img loads, accessing it right away and making a canvas will not work since the img hasn’t loaded yet. So i added a listener for load.
> Fix Chase cars icons not showing on map

- DEVELOPER_README.md
Some quick notes to help folks get started, ref #246
> adding DEVELOPER_README.md

- js/tracker.js
Not sure if this was intended to not be added, but I find this feature useful when I'm wanting to look for directions when determining if I want to chase a sonde if it landed nearby.
The UI is the exact same as on other platforms, however when clicking on the link you are taken to Google Maps in a new tab.
I'm not sure if it's possible to assign a marker with a name on it like Android can, but this is a simple change to enable clickable coordinates on the desktop
> Add a link to view a sonde on Google Maps on PCs

- js/tracker.js
> Flatten ctx loop. Move chase car to buffer

- README.md
Fixed the markdown typo of the HabHub Tracker link in the `README.md` file
> README.md link typo fixed

- js/tracker.js
Reinstates landing predictions for landed sondes.
I have tested this but would appreciate a review as I don't understand the other code in updatePredictions() - hence draft pull request!
> fixes #317

- js/tracker.js
When viewing SondeHub, a user will see some number of balloons in their view. Balloons are colored with a few different colors, to make it easy to tell them apart.
Currently, the color is selected by iterating through all the balloons, one by one, and each balloon gets a color from the list of colors, sequentially. Because balloons are iterated through in a non-deterministic manner (such that inserting or removing one balloon from the set will change the outcome of the others), viewing the set of balloons multiple times will result in the colors becoming re-shuffled. Therefore, refreshing the page, or viewing it on multiple devices (including viewing the site alongside a friend) will mean the same balloon will appear with different colors on different viewings.
This PR changes the logic …
> Change balloon color selection to be stable per-balloon

- img/markers/balloon.svg
- img/markers/parachute.svg
It was noted that the new SVGs are hard to read on the DarkMatter background map. This adds a white drop shadow onto the strings which looks much better, as seen in the below screenshot.
> Add white shadow to parachute/balloon strings

- js/app.js
- js/station.js
- js/tracker.js
In a couple places, it's possible to click on coordinates to bring up an external mapping application:
* sidebar (balloon / chase car details)
* landing prediction popup
Elsewhere, coordinates are displayed as plain text. It would be convenient to have coordinates displayed as a clickable link everywhere.
Here I extracted the common code for generating a link into a function (`format_coordinates`), and used it to display coordinates in the following places:
* historical landing popup
* balloon path popup
* recovery popup
* recoveries pane
> Make coordinates clickable everywhere

- js/tracker.js
As noted in https://github.com/projecthorus/sondehub-tracker/pull/335#issuecomment-2393849926, choosing a new time period in the drop down menu results in an exception. I had a look over the code changes in #335 and tracked down the bug. Also, I noticed a couple other bugs which I've corrected here.
/cc @TheSkorm
> Fix prediction polyline bugs

- js/app.js
In the Chase Mode section, if "Enable" is toggled before a callsign is first set, then an exception occurs and the user gets no feedback:
> Uncaught TypeError: callsign is null
This only happens if a callsign has never been set, and therefore no `callsign` value exists in local storage.
I've fixed the null check so that the user gets an alert popup when no callsign has been set.
> Fix callsign null check

- js/sondehub.js
As noted in https://github.com/projecthorus/sondehub-tracker/pull/335#issuecomment-2418441992, clicking on a prediction or reverse prediction produces a popup that says "Length: NaN km".
I fixed this by moving `path_length` onto the individual line objects.
/cc @TheSkorm
> Fix prediction length popup

- .gitignore
- DEVELOPER_README.md
- build.sh
- index.template.html
- js/app.js
- service-worker.template.js
In #341 I made `service-worker.js` static, but I realized after the fact that this will likely break PWA updating, because devices check for updates by looking for changes in `manifest.json` or `service-worker.js`.
Here I've switched back to a templated `service-worker.js`, which is generated from `service-worker.template.js`.
Additionally, I realized that there wasn't match point having the now-static `app.js` pull the version information from `index.html` and dump it back in, so I moved that information directly into `index.html`.
> Fix PWA caching

- js/app.js
- service-worker.template.js
`tracker.js` has been renamed to `sondehub.js`, so references to it should be updated as well.
> Update references to sondehub.js

- js/sondehub.js
Between visits to sondehub-tracker, settings and map layer are preserved. But map coordinates, zoom level, and time period are not preserved, and default values are used instead. I think it would be useful to save & restore these additional values, so I've done so here.
> Save & restore map coordinates and zoom
